### ISSUE TITLE
TODO after finishing stage 2

### ISSUE THREAD

**Issue by saketba** [hurb404/hotline#3]
- [ ] Figure out special character 
- [ ] Fix variable naming
.
.
.
.
.
- [ ] Special character: putting more than 2 results in an error
- [ ] Special character: putting 2 reduces the output length by 1
- [ ] Special character: putting 1 works fine

Everything else works fine
_Might have to add checks for special characters in the first linear search_
